# -*- coding: utf-8 -*-
"""coffee_severity_estimation_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMgqWFc27HhVYcTTaFM1GLPWUg3oGSgI
"""

from google.colab import drive
drive.mount('/content/drive')

import torch
from architectures import load_model
# build the same network architecture
model_path= r"/content/drive/MyDrive/AI_Dataset_551_553_574/Model_results/segmentation_results/trial10/net_weights.pth"
model = load_model("pspresnet50", model_path)
model.eval()

if torch.cuda.is_available():
    model.cuda()

!git clone https://github.com/esgario/lara2018.git

# Commented out IPython magic to ensure Python compatibility.
# %cd .

print(next(model.parameters()).device)

import os
from PIL import Image
import numpy as np

# Change to the correct directory first
os.chdir("/content/lara2018/segmentation")

# Now use relative path from here
image_path = "dataset/images/test/1517.jpg"

# Or if it's deeply nested
if not os.path.exists(image_path):
    # Try going deeper
    os.chdir("/content/lara2018/segmentation/lara2018/segmentation")
    image_path = "dataset/images/test/1517.jpg"

# Load the image
if os.path.exists(image_path):
    image = np.array(Image.open(image_path).convert("RGB"))
    print(f"✓ Success! Image shape: {image.shape}")
else:
    print(f"File not found at {os.path.abspath(image_path)}")

from PIL import Image
import numpy as np
import torch
import matplotlib.pyplot as plt

# load image
img = Image.open(image_path).convert("RGB")

# resize safely using PIL
img_resized = img.resize((256, 256))

# convert to numpy
image_np = np.array(img_resized)

print(image_np.shape)

print(type(image_np))
print(image_np.shape)
print(image_np.dtype)
print(image_np.min(), image_np.max())

from PIL import Image

img = Image.fromarray(image_np)
img.save("leaf_image.png")

print("Saved successfully")

input_tensor = torch.tensor(image_np, dtype=torch.float32)
input_tensor = input_tensor.permute(2, 0, 1) / 255.0
input_tensor = input_tensor.unsqueeze(0)

# move to GPU if available
if torch.cuda.is_available():
    input_tensor = input_tensor.cuda()
    model = model.cuda()

# ---------- PREDICT ----------
model.eval()

with torch.no_grad():
    output = model(input_tensor)

# if model returns tuple (PSPNet usually does)
if isinstance(output, tuple):
    output = output[0]

# multiclass prediction
pred_mask = torch.argmax(output, dim=1)

# remove batch dimension
mask = pred_mask.squeeze().cpu().numpy().astype(np.uint8)

print("Mask shape:", mask.shape)
print("Unique values:", np.unique(mask))

from PIL import Image
import numpy as np

# convert 0/1 mask to visible 0/255 image
mask_vis = (mask * 255).astype(np.uint8)

# create PIL image
mask_img = Image.fromarray(mask_vis)

# save
mask_img.save("predicted_mask.png")

print("Mask saved as predicted_mask.png")

mask_img.show()

from PIL import Image
import numpy as np

overlay = image_np.copy()

# mark diseased pixels in red
overlay[mask == 1] = [255, 0, 0]

overlay_img = Image.fromarray(overlay.astype(np.uint8))
overlay_img.save("overlay_mask.png")
overlay_img.show()

#check with ground truth
from PIL import Image
import numpy as np

gt_path = r"lara2018/segmentation/dataset/annotations/test/1517_mask.png"
    # same image's mask

gt = Image.open(gt_path).convert("L")
gt = gt.resize((256, 256))

gt_np = np.array(gt)

print("GT unique:", np.unique(gt_np))
print("Pred unique:", np.unique(mask))

gt_class = np.zeros_like(gt_np)

gt_class[gt_np == 76] = 1
gt_class[gt_np == 103] = 2

print("Converted GT unique:", np.unique(gt_class))

pred_bin = (mask == 1).astype(np.uint8)
gt_bin = (gt_class > 0).astype(np.uint8)

intersection = np.logical_and(pred_bin, gt_bin).sum()
union = np.logical_or(pred_bin, gt_bin).sum()

iou = intersection / union if union > 0 else 0
print("Lesion IoU:", iou)

from PIL import Image
import numpy as np

# original resized image
orig = image_np.copy()

# mark predicted lesion in red
overlay = orig.copy()
overlay[mask == 1] = [255, 0, 0]

overlay_img = Image.fromarray(overlay.astype(np.uint8))
overlay_img.save("lesion_overlay.png")
overlay_img.show()

lesion_pixels = np.sum(mask == 1)
total_pixels = mask.size

print("Lesion pixels:", lesion_pixels)
print("Total pixels:", total_pixels)
print("Predicted severity %:", lesion_pixels / total_pixels * 100)

gt_lesion = np.sum(gt_np > 0)
gt_total = gt_np.size

gt_severity = (gt_lesion / gt_total) * 100

print(f"GT severity: {gt_severity:.2f}%")
print(f"Pred severity: {lesion_pixels / total_pixels * 100:.2f}%")

from PIL import Image
import numpy as np

orig = Image.fromarray(image_np.astype(np.uint8)).convert("RGBA")

# transparent overlay
red_mask = np.zeros((256, 256, 4), dtype=np.uint8)

# RGBA = red with transparency
red_mask[mask == 1] = [255, 0, 0, 120]

mask_overlay = Image.fromarray(red_mask, mode="RGBA")

# combine
result = Image.alpha_composite(orig, mask_overlay)

result.save("transparent_disease_overlay.png")
result.show()

print("Saved as transparent_disease_overlay.png")

disease_only = np.zeros_like(image_np)
disease_only[mask == 1] = image_np[mask == 1]

Image.fromarray(disease_only).save("diseased_region_only.png")

# Create a folder for new test images
import os

# Create directory structure
os.makedirs("new_test_images", exist_ok=True)
os.makedirs("new_test_results", exist_ok=True)

# Copy your new coffee leaf images to "new_test_images/" folder

# Create folder in your Drive
from google.colab import drive
drive.mount('/content/drive')

# Create test folder in Drive
os.makedirs("/content/drive/MyDrive/test_coffee_leaves", exist_ok=True)

print("✅ Created folder in Google Drive")
print("📍 Location: /content/drive/MyDrive/test_coffee_leaves")

# Modified prediction with confidence filtering

def predict_with_confidence(image_tensor, model, confidence_threshold=0.7):
    """
    Only classify pixels as diseased if model confidence > threshold
    """
    model.eval()
    with torch.no_grad():
        output = model(image_tensor)
        if isinstance(output, tuple):
            output = output[0]

        # Get probabilities using softmax
        probs = torch.softmax(output, dim=1)

        # Get predicted class and confidence
        pred_mask = torch.argmax(output, dim=1)
        confidence = torch.max(probs, dim=1)[0]

        # Apply confidence threshold
        mask = pred_mask.squeeze().cpu().numpy().astype(np.uint8)
        conf = confidence.squeeze().cpu().numpy()

        # Only keep disease pixels with high confidence
        mask_filtered = np.where((mask == 1) & (conf >= confidence_threshold), 1, 0)

    return mask_filtered, conf

# Modified code to process ALL images correctly
import torch
import sys
import os
import glob
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy import ndimage

sys.path.insert(0, '/content/lara2018/segmentation')
from architectures import load_model

# Load model
model_path = r"/content/drive/MyDrive/AI_Dataset_551_553_574/Model_results/segmentation_results/trial10/net_weights.pth"
model = load_model("pspresnet50", model_path)
model.eval()

if torch.cuda.is_available():
    model.cuda()
    print("✅ Model loaded on GPU")

TEST_FOLDER = "test_images"

# Higher confidence threshold to reduce false positives
CONFIDENCE_THRESHOLD = 0.85  # Increased from 0.75

# ADDITIONAL: Minimum lesion size to be considered disease
MIN_LESION_PIXELS = 500  # At least 500 pixels (about 0.8% of image)

def predict_with_multiple_filters(image_np, model, conf_threshold=0.85, min_lesion=500):
    """Multiple filters to reduce false positives"""

    input_tensor = torch.tensor(image_np, dtype=torch.float32)
    input_tensor = input_tensor.permute(2, 0, 1) / 255.0
    input_tensor = input_tensor.unsqueeze(0)

    if torch.cuda.is_available():
        input_tensor = input_tensor.cuda()

    model.eval()
    with torch.no_grad():
        output = model(input_tensor)
        if isinstance(output, tuple):
            output = output[0]

        probs = torch.softmax(output, dim=1)
        pred_mask = torch.argmax(output, dim=1)
        confidence = torch.max(probs, dim=1)[0]

        mask = pred_mask.squeeze().cpu().numpy().astype(np.uint8)
        conf = confidence.squeeze().cpu().numpy()

        # Filter 1: Confidence threshold
        mask_filtered = np.where((mask == 1) & (conf >= conf_threshold), 1, 0)

        # Filter 2: Remove small isolated regions (noise)
        mask_filtered = ndimage.binary_opening(mask_filtered, structure=np.ones((3,3))).astype(np.uint8)
        mask_filtered = ndimage.binary_closing(mask_filtered, structure=np.ones((3,3))).astype(np.uint8)

        # Filter 3: Minimum lesion size
        labeled, num_features = ndimage.label(mask_filtered)
        for i in range(1, num_features + 1):
            if np.sum(labeled == i) < min_lesion:
                mask_filtered[labeled == i] = 0

    return mask_filtered, conf, mask

# Find ALL images
image_extensions = ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG']
test_images = []
for ext in image_extensions:
    test_images.extend(glob.glob(os.path.join(TEST_FOLDER, ext)))

# Remove result images from test set (only process original images)
test_images = [img for img in test_images if not img.startswith('result_')]

print(f"\n📸 Found {len(test_images)} original images")
print(f"🔧 Filters: Confidence={CONFIDENCE_THRESHOLD}, Min Lesion={MIN_LESION_PIXELS} pixels")
print("="*70)

results_list = []

for idx, image_path in enumerate(test_images, 1):
    print(f"\n{'='*70}")
    print(f"🖼️  Testing Image {idx}/{len(test_images)}: {os.path.basename(image_path)}")
    print(f"{'='*70}")

    # Load image
    img = Image.open(image_path).convert("RGB")
    img_resized = img.resize((256, 256))
    image_np = np.array(img_resized)

    # Get filtered mask
    mask_filtered, confidence, mask_original = predict_with_multiple_filters(
        image_np, model, CONFIDENCE_THRESHOLD, MIN_LESION_PIXELS
    )

    # Calculate severities
    lesion_pixels_filtered = np.sum(mask_filtered == 1)
    lesion_pixels_original = np.sum(mask_original == 1)
    total_pixels = mask_filtered.size

    severity_pct_filtered = (lesion_pixels_filtered / total_pixels) * 100
    severity_pct_original = (lesion_pixels_original / total_pixels) * 100

    # Calculate confidence stats
    if lesion_pixels_filtered > 0:
        avg_confidence = confidence[mask_filtered == 1].mean()
        max_confidence = confidence[mask_filtered == 1].max()
    else:
        avg_confidence = 0
        max_confidence = 0

    print(f"\n📊 Filtering Results:")
    print(f"   Original prediction: {severity_pct_original:.2f}%")
    print(f"   After filtering: {severity_pct_filtered:.2f}%")
    print(f"   Reduction: {(severity_pct_original - severity_pct_filtered):.2f}%")
    print(f"   Avg confidence: {avg_confidence:.3f}")
    print(f"   Lesion pixels: {lesion_pixels_filtered:,} / {total_pixels:,}")

    # **CRITICAL: Verify if image is actually diseased**
    is_considered_diseased = severity_pct_filtered > 5  # At least 5% affected

    # Determine severity class
    if not is_considered_diseased or severity_pct_filtered < 5:
        severity_class = "Healthy"
        severity_level = 0
        recommendation = "✅ HEALTHY - No disease detected"
        severity_pct_filtered = 0  # Force to 0 for healthy
        print(f"\n⚠️  Image classified as HEALTHY (filtered severity below threshold)")
    elif severity_pct_filtered < 15:
        severity_class = "Very Low"
        severity_level = 1
        recommendation = "🟢 Very Low - Monitor weekly"
    elif severity_pct_filtered < 30:
        severity_class = "Low"
        severity_level = 2
        recommendation = "🟡 Low - Consider preventive treatment"
    elif severity_pct_filtered < 50:
        severity_class = "Moderate"
        severity_level = 3
        recommendation = "🟠 Moderate - Apply treatment"
    else:
        severity_class = "High"
        severity_level = 4
        recommendation = "🔴 SEVERE - Immediate treatment required"

    print(f"\n✅ FINAL DIAGNOSIS:")
    print(f"   Severity: {severity_pct_filtered:.2f}%")
    print(f"   Class: {severity_class}")
    print(f"   {recommendation}")

    # Visualization
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))

    # Row 1
    axes[0, 0].imshow(image_np)
    axes[0, 0].set_title(f'Original: {os.path.basename(image_path)}', fontsize=12)
    axes[0, 0].axis('off')

    mask_vis_original = (mask_original * 255).astype(np.uint8)
    axes[0, 1].imshow(mask_vis_original, cmap='Reds')
    axes[0, 1].set_title(f'Raw Prediction\n{severity_pct_original:.1f}%', fontsize=12)
    axes[0, 1].axis('off')

    im = axes[0, 2].imshow(confidence, cmap='hot', vmin=0, vmax=1)
    axes[0, 2].set_title(f'Confidence Map\nThreshold: {CONFIDENCE_THRESHOLD}', fontsize=12)
    axes[0, 2].axis('off')
    plt.colorbar(im, ax=axes[0, 2], fraction=0.046, pad=0.04)

    # Row 2
    mask_vis_filtered = (mask_filtered * 255).astype(np.uint8)
    axes[1, 0].imshow(mask_vis_filtered, cmap='Reds')
    axes[1, 0].set_title(f'Filtered Prediction\n{severity_pct_filtered:.1f}%', fontsize=12)
    axes[1, 0].axis('off')

    overlay_filtered = image_np.copy()
    overlay_filtered[mask_filtered == 1] = [255, 0, 0]
    axes[1, 1].imshow(overlay_filtered)
    axes[1, 1].set_title(f'Final Overlay\nClass: {severity_class}', fontsize=12)
    axes[1, 1].axis('off')

    # Show filtered-out regions
    false_positives = (mask_original == 1) & (mask_filtered == 0)
    diff_vis = image_np.copy()
    diff_vis[false_positives] = [255, 255, 0]
    axes[1, 2].imshow(diff_vis)
    axes[1, 2].set_title(f'Removed (False Positives)\n{np.sum(false_positives)} pixels', fontsize=12)
    axes[1, 2].axis('off')

    plt.suptitle(f'Diagnosis: {severity_class} ({severity_pct_filtered:.1f}%)', fontsize=14, fontweight='bold')
    plt.tight_layout()

    # Save
    result_filename = f"result_{idx}_{os.path.basename(image_path).replace('.jpg', '.png')}"
    plt.savefig(os.path.join(TEST_FOLDER, result_filename), dpi=150, bbox_inches='tight')
    plt.show()

    # Store results
    results_list.append({
        'image': os.path.basename(image_path),
        'raw_severity_%': round(severity_pct_original, 2),
        'final_severity_%': round(severity_pct_filtered, 2),
        'severity_class': severity_class,
        'severity_level': severity_level,
        'avg_confidence': round(avg_confidence, 3),
        'false_positives_removed': int(np.sum(false_positives)),
        'recommendation': recommendation
    })

# Summary
print("\n" + "="*70)
print("📊 FINAL SUMMARY - All Test Images")
print("="*70)

df_results = pd.DataFrame(results_list)
print(df_results.to_string(index=False))

# Save CSV
csv_path = os.path.join(TEST_FOLDER, "test_final_results.csv")
df_results.to_csv(csv_path, index=False)

print(f"\n💾 Results saved to: {csv_path}")
print("\n📈 Statistics:")
print(f"   Images tested: {len(df_results)}")
print(f"   Healthy images detected: {len(df_results[df_results['severity_class'] == 'Healthy'])}")
print(f"   Average final severity: {df_results['final_severity_%'].mean():.2f}%")

print("\n✅ Testing complete!")

# Commented out IPython magic to ensure Python compatibility.
# %cd lara2018

# Commented out IPython magic to ensure Python compatibility.
# %cd classification

# Commented out IPython magic to ensure Python compatibility.
# %cd architectures

# ============================================
# CLASSIFICATION MODEL TESTING
# ResNet50 vs MobileNetV2 - Severity Estimation
# WITH UPLOAD PROMPT
# ============================================

import torch
import torch.nn as nn
import os
import sys
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import time

# ============================================
# STEP 1: IMPORT MODELS (Direct imports)
# ============================================

# Change to architectures folder
os.chdir('/content/lara2018/classification/architectures')
print(f"📂 Current directory: {os.getcwd()}")

# Import models directly
from resnet import resnet50
from mobilenetv2 import mobilenet_v2

print("✅ Models imported successfully!")

# ============================================
# STEP 2: SETUP
# ============================================

# Create a NEW folder for classification test images
CLASSIFICATION_TEST_FOLDER = "classification_test_images"

# Severity class names
SEVERITY_CLASSES = ['Healthy', 'Very Low', 'Low', 'High', 'Very High']

# Model paths
MODEL_PATHS = {
    'resnet50': '/content/drive/MyDrive/AI_Dataset_551_553_574/Model_results/net_weights_resnet50.pth',
    'mobilenet_v2': '/content/drive/MyDrive/AI_Dataset_551_553_574/Model_results/net_weights_mobilenet_v2.pth'
}

# ============================================
# STEP 3: CREATE FOLDER AND PROMPT FOR UPLOAD
# ============================================

# Create the test folder in /content (not in lara2018)
test_folder_path = f"/content/{CLASSIFICATION_TEST_FOLDER}"
os.makedirs(test_folder_path, exist_ok=True)

print("\n" + "="*60)
print("📁 CLASSIFICATION TEST FOLDER CREATED")
print("="*60)
print(f"📍 Folder path: {test_folder_path}")
print("\n⚠️  PLEASE UPLOAD YOUR TEST IMAGES to this folder!")
print("   In Colab: Left sidebar → Folder icon → classification_test_images → Upload")
print("\n📸 Upload images of coffee leaves (any plant leaves you want to test)")
print("   Supported formats: .jpg, .jpeg, .png")
print("\n👉 AFTER UPLOADING, PRESS ENTER TO CONTINUE...")
input()

# ============================================
# STEP 4: LOAD MODELS
# ============================================

def load_model_with_weights(model_constructor, weights_path, model_name, num_classes=5):
    """Load trained model with weights"""
    print(f"\n📦 Loading {model_name} from: {weights_path}")

    if not os.path.exists(weights_path):
        print(f"❌ File not found: {weights_path}")
        return None

    try:
        model = model_constructor(pretrained=False, num_classes=num_classes)
        state_dict = torch.load(weights_path, map_location='cpu')

        # Remove 'module.' prefix if present
        new_state_dict = {}
        for k, v in state_dict.items():
            name = k.replace('module.', '')
            new_state_dict[name] = v

        model.load_state_dict(new_state_dict, strict=False)

        if torch.cuda.is_available():
            model = model.cuda()

        model.eval()
        print(f"✅ {model_name} loaded successfully")
        return model

    except Exception as e:
        print(f"❌ Error loading {model_name}: {e}")
        return None

print("\n" + "="*60)
print("🔧 LOADING TRAINED MODELS")
print("="*60)

# Mount drive if not mounted
from google.colab import drive
drive.mount('/content/drive')

loaded_models = {}

for model_name, model_path in MODEL_PATHS.items():
    if model_name == 'resnet50':
        model = load_model_with_weights(resnet50, model_path, model_name)
    else:
        model = load_model_with_weights(mobilenet_v2, model_path, model_name)

    if model:
        loaded_models[model_name] = model

if len(loaded_models) == 0:
    print("\n❌ No models loaded. Please check file paths.")
    exit()

print(f"\n✅ Successfully loaded {len(loaded_models)} model(s): {list(loaded_models.keys())}")

# ============================================
# STEP 5: PREPROCESSING AND PREDICTION FUNCTIONS
# ============================================

def preprocess_image(image_path, target_size=(224, 224)):
    """Preprocess image for classification"""
    img = Image.open(image_path).convert("RGB")
    img = img.resize(target_size)

    img_array = np.array(img).astype(np.float32) / 255.0
    img_tensor = torch.from_numpy(img_array).permute(2, 0, 1)

    # ImageNet normalization
    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
    img_tensor = (img_tensor - mean) / std

    return img_tensor.unsqueeze(0)

def predict_severity(model, image_path):
    """Predict severity class for a single image"""
    img_tensor = preprocess_image(image_path)

    if torch.cuda.is_available():
        img_tensor = img_tensor.cuda()

    with torch.no_grad():
        output = model(img_tensor)

        # Handle multi-task output
        if isinstance(output, tuple):
            output = output[1] if len(output) >= 2 else output[0]

        probabilities = torch.softmax(output, dim=1)
        predicted_class = torch.argmax(probabilities, dim=1).item()
        confidence = probabilities[0, predicted_class].item()
        prob_distribution = probabilities.cpu().numpy()[0]

    return {
        'severity_class': predicted_class,
        'severity_label': SEVERITY_CLASSES[predicted_class],
        'confidence': confidence,
        'probabilities': prob_distribution
    }

# ============================================
# STEP 6: GET TEST IMAGES
# ============================================

# Get all test images from the upload folder
test_images = []
for ext in ['*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG']:
    test_images.extend(glob.glob(os.path.join(test_folder_path, ext)))

print(f"\n📸 Found {len(test_images)} test images:")
for img in test_images:
    print(f"   - {os.path.basename(img)}")

if len(test_images) == 0:
    print("\n❌ No images found! Please upload images to the folder and rerun.")
    print(f"   Folder: {test_folder_path}")
    exit()

# ============================================
# STEP 7: TEST ALL IMAGES
# ============================================

print("\n" + "="*80)
print("📊 CLASSIFICATION MODEL COMPARISON")
print("="*80)

results = []
result_images_folder = os.path.join(test_folder_path, "results")
os.makedirs(result_images_folder, exist_ok=True)

for idx, img_path in enumerate(test_images, 1):
    print(f"\n{'='*60}")
    print(f"🖼️  Testing Image {idx}/{len(test_images)}: {os.path.basename(img_path)}")
    print(f"{'='*60}")

    predictions = {}

    for model_name, model in loaded_models.items():
        pred = predict_severity(model, img_path)
        predictions[model_name] = pred

        print(f"\n🔍 {model_name.upper()} Results:")
        print(f"   → Predicted: {pred['severity_label']} (Level {pred['severity_class']})")
        print(f"   → Confidence: {pred['confidence']:.2%}")
        print(f"   → Probability Distribution:")
        for i, prob in enumerate(pred['probabilities'][:5]):
            bar = "█" * int(prob * 50)
            print(f"      {SEVERITY_CLASSES[i]:12s}: {prob:6.2%} {bar}")

    # Create visualization
    img = Image.open(img_path)
    img_display = img.resize((250, 250))

    fig, axes = plt.subplots(1, len(loaded_models) + 1, figsize=(5*(len(loaded_models)+1), 4))

    # Original image
    axes[0].imshow(img_display)
    axes[0].set_title(f"Original Image\n{os.path.basename(img_path)}", fontsize=10, fontweight='bold')
    axes[0].axis('off')

    # Predictions
    colors = ['green', 'lightgreen', 'gold', 'orange', 'red']

    for i, (model_name, pred) in enumerate(predictions.items(), 1):
        axes[i].imshow(img_display)

        # Add colored bordered
        for spine in axes[i].spines.values():
            spine.set_edgecolor(colors[pred['severity_class']])
            spine.set_linewidth(4)

        title = f"{model_name.upper()}\n{pred['severity_label']}\nConf: {pred['confidence']:.1%}"
        axes[i].set_title(title, fontsize=10, fontweight='bold')
        axes[i].axis('off')

    plt.tight_layout()
    save_path = os.path.join(result_images_folder, f"result_{idx}_{os.path.basename(img_path).replace('.jpg', '.png')}")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()

    # Store results
    row = {'image': os.path.basename(img_path)}
    for model_name, pred in predictions.items():
        row[f'{model_name}_class'] = pred['severity_label']
        row[f'{model_name}_level'] = pred['severity_class']
        row[f'{model_name}_confidence'] = pred['confidence']
    results.append(row)

# ============================================
# STEP 8: COMPREHENSIVE SUMMARY
# ============================================

print("\n" + "="*80)
print("📈 FINAL SUMMARY - MODEL COMPARISON")
print("="*80)

df_results = pd.DataFrame(results)

# Display results table
print("\n📊 Detailed Results Table:")
print(df_results.to_string(index=False))

# Average confidence by model
print("\n📊 Average Confidence by Model:")
for model_name in loaded_models.keys():
    avg_conf = df_results[f'{model_name}_confidence'].mean()
    std_conf = df_results[f'{model_name}_confidence'].std()
    print(f"   {model_name.upper()}: {avg_conf:.2%} ± {std_conf:.2%}")

# Agreement between models
if len(loaded_models) >= 2:
    model_names = list(loaded_models.keys())
    agreement = (df_results[f'{model_names[0]}_level'] == df_results[f'{model_names[1]}_level']).mean()
    print(f"\n🤝 Agreement between models: {agreement:.1%}")

    if agreement < 1.0:
        print(f"\n⚠️  Disagreements found:")
        for _, row in df_results.iterrows():
            if row[f'{model_names[0]}_level'] != row[f'{model_names[1]}_level']:
                print(f"   {row['image']}: {model_names[0]}={row[f'{model_names[0]}_class']}, {model_names[1]}={row[f'{model_names[1]}_class']}")

# Best model per image
print(f"\n🏆 Best Model per Image (Higher Confidence):")
for _, row in df_results.iterrows():
    best_model = max(loaded_models.keys(), key=lambda m: row[f'{m}_confidence'])
    best_conf = row[f'{best_model}_confidence']
    print(f"   {row['image']}: {best_model.upper()} (conf: {best_conf:.1%})")

# Overall best model
overall_best = max(loaded_models.keys(), key=lambda m: df_results[f'{m}_confidence'].mean())
overall_best_conf = df_results[f'{overall_best}_confidence'].mean()

print(f"\n🎯 OVERALL BEST MODEL: {overall_best.upper()}")
print(f"   Average confidence: {overall_best_conf:.2%}")
print(f"   Recommendation: Use {overall_best.upper()} for severity estimation")

# ============================================
# STEP 9: SAVE RESULTS
# ============================================

# Save CSV
csv_path = os.path.join(test_folder_path, "classification_results.csv")
df_results.to_csv(csv_path, index=False)
print(f"\n💾 Results saved to: {csv_path}")

# Save summary report
summary_path = os.path.join(test_folder_path, "summary_report.txt")
with open(summary_path, 'w') as f:
    f.write("="*60 + "\n")
    f.write("CLASSIFICATION MODEL COMPARISON REPORT\n")
    f.write("="*60 + "\n\n")
    f.write(f"Test images: {len(test_images)}\n")
    f.write(f"Models tested: {', '.join(loaded_models.keys())}\n\n")

    f.write("Average Confidence:\n")
    for model_name in loaded_models.keys():
        avg_conf = df_results[f'{model_name}_confidence'].mean()
        f.write(f"  {model_name.upper()}: {avg_conf:.2%}\n")

    f.write(f"\nBest Model Overall: {overall_best.upper()}\n")
    f.write(f"Best Model Confidence: {overall_best_conf:.2%}\n")

print(f"💾 Summary saved to: {summary_path}")

# ============================================
# STEP 10: FINAL RECOMMENDATION
# ============================================

print("\n" + "="*80)
print("✅ TESTING COMPLETE!")
print("="*80)
print(f"\n📁 All results saved in: {test_folder_path}")
print(f"   - Results CSV: classification_results.csv")
print(f"   - Summary report: summary_report.txt")
print(f"   - Visualizations: results/ folder")
print(f"\n🏆 Use {overall_best.upper()} for your severity estimation pipeline!")

# Optional: Show severity distribution
print("\n📊 Severity Distribution by Model:")
for model_name in loaded_models.keys():
    print(f"\n   {model_name.upper()}:")
    dist = df_results[f'{model_name}_class'].value_counts()
    for severity, count in dist.items():
        print(f"      {severity}: {count} image(s)")